### ISSUE TITLE
How  to  read loom  to  velociraptor? 

### ISSUE THREAD

**Issue by tuqiang2014** [kevinrue/velociraptor#31] opened 2021-01-13 04:10 UTC
hi,

run  velocyto   out file  is  loom  , how  to  read loom  into  velociraptor?

**Comment by csoneson** [comment] 2021-01-13 07:26
Have a look at the `import` function from the `LoomExperiment` package (https://www.bioconductor.org/packages/LoomExperiment/).

**Comment by csoneson** [comment] 2021-01-28 10:10
I will close this issue - feel free to reopen if the suggestion above did not solve your problem.

**Closed by csoneson** 2021-01-28 10:10 UTC

**Comment by iheartfoosball** [comment] 2021-07-27 21:27
Hi! Does it matter how the loom file was generated? I am having some issues trying to use a loom file made using the loompy `fromq `[command ](https://linnarssonlab.org/loompy/kallisto/index.html#using-the-loompy-fromfq-command). Basically I did:

```
library(LoomExperiment)
myloom <- import(path, type="SingleCellLoomExperiment")

library(velociraptor)
velo.out <- scvelo(myloom, assay.X="spliced")
```

and I get this:

```
Error in py_set_attr_impl(x, name, value) :
  TypeError: object of type 'NoneType' has no len()

Detailed traceback:
  File "/home/ktessema/.cache/basilisk/1.2.1/velociraptor-1.0.0/env/lib/python3.                                                 7/site-packages/anndata/_core/anndata.py", line 847, in obs_names
    names = self._prep_dim_index(names, "obs")
  File "/home/ktessema/.cache/basilisk/1.2.1/velociraptor-1.0.0/env/lib/python3.                                                 7/site-packages/anndata/_core/anndata.py", line 794, in _prep_dim_index
    if self.shape[attr == "var"] != len(value):
```

Any idea why this may happen?

Thanks!

**Comment by csoneson** [comment] 2021-07-28 07:48
It's not directly obvious to me what's happening here (maybe someone else has an idea) - could you give some more information about your object (e.g., what do you get if you print out `myloom`)? I also notice that you are using old versions of the packages - you could see if the issue is resolved by updating to the current Bioc release.

**Comment by iheartfoosball** [comment] 2021-07-28 20:03
Thanks! I don't have admin privileges on that cluster so I'm limited in terms of updates. Below is the `myloom` info. I feel like the loom file might be problematic, but I'm not sure. I will try generating the loom file using velocyto instead of loompy. There may also be a way to modify this loom file to make it readable by the `scvelo` command, but I'm not experienced enough to figure that out quickly 😅

```
class: SingleCellLoomExperiment 
dim: 60662 1076 
metadata(18): last_modified AmbientPValue ... targetnumcells technology
assays(3): matrix spliced unspliced
rownames: NULL
rowData names(27): Accession AccessionVersion ... UniprotID VegaID
colnames: NULL
colData names(2): CellID TotalUMIs
reducedDimNames(0):
mainExpName: NULL
altExpNames(0):
rowGraphs(0): NULL
colGraphs(0): NULL
```

I've also been trying to do this on my PC, where I actually can't even run the velociraptor vignette. I get the same error regardless of which file I use as the input to `scvelo` (vignette sce vs my loom file imported via LoomExperiment, as in previous comment). I believe everything is up to date. Seems like a windows issue but I honestly have no clue.

```
> library(scRNAseq)
> sce <- HermannSpermatogenesisData()
snapshotDate(): 2021-05-18
see ?scRNAseq and browseVignettes('scRNAseq') for documentation
loading from cache
see ?scRNAseq and browseVignettes('scRNAseq') for documentation
loading from cache
see ?scRNAseq and browseVignettes('scRNAseq') for documentation
loading from cache
> sce
class: SingleCellExperiment 
dim: 54448 2325 
metadata(0):
assays(2): spliced unspliced
rownames(54448): ENSMUSG00000102693.1 ENSMUSG00000064842.1 ... ENSMUSG00000064369.1
  ENSMUSG00000064372.1
rowData names(0):
colnames(2325): CCCATACTCCGAAGAG AATCCAGTCATCTGCC ... ATCCACCCACCACCAG
  ATTGGTGGTTACCGAT
colData names(1): celltype
reducedDimNames(0):
mainExpName: NULL
altExpNames(0):
> sce <- sce[, 1:500]
> library(scuttle)
> sce <- logNormCounts(sce, assay.type=1)
> library(scran)
> dec <- modelGeneVar(sce)
Warning message:
In regularize.values(x, y, ties, missing(ties), na.rm = na.rm) :
  collapsing to unique 'x' values
> top.hvgs <- getTopHVGs(dec, n=2000)
> library(velociraptor)
> velo.out <- scvelo(sce, subset.row=top.hvgs, assay.X="spliced")
Error in py_module_import(module, convert = convert) : 
  OSError: [WinError 6] The handle is invalid
```

Session info:
```
> sessionInfo()
R version 4.1.0 (2021-05-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19043)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] velociraptor_1.2.0          scran_1.20.1                scuttle_1.2.0              
 [4] scRNAseq_2.6.1              LoomExperiment_1.10.1       BiocIO_1.2.0               
 [7] rhdf5_2.36.0                SingleCellExperiment_1.14.1 SummarizedExperiment_1.22.0
[10] Biobase_2.52.0              GenomicRanges_1.44.0        GenomeInfoDb_1.28.1        
[13] IRanges_2.26.0              MatrixGenerics_1.4.0        matrixStats_0.60.0         
[16] S4Vectors_0.30.0            BiocGenerics_0.38.0        

loaded via a namespace (and not attached):
  [1] rjson_0.2.20                  ellipsis_0.3.2                bluster_1.2.1                
  [4] XVector_0.32.0                BiocNeighbors_1.10.0          bit64_4.0.5                  
  [7] interactiveDisplayBase_1.30.0 AnnotationDbi_1.54.1          fansi_0.5.0                  
 [10] xml2_1.3.2                    sparseMatrixStats_1.4.0       cachem_1.0.5                 
 [13] jsonlite_1.7.2                Rsamtools_2.8.0               cluster_2.1.2                
 [16] dbplyr_2.1.1                  png_0.1-7                     shiny_1.6.0                  
 [19] HDF5Array_1.20.0              BiocManager_1.30.16           compiler_4.1.0               
 [22] httr_1.4.2                    basilisk_1.4.0                dqrng_0.3.0                  
 [25] lazyeval_0.2.2                assertthat_0.2.1              Matrix_1.3-4                 
 [28] fastmap_1.1.0                 limma_3.48.1                  later_1.2.0                  
 [31] BiocSingular_1.8.1            htmltools_0.5.1.1             prettyunits_1.1.1            
 [34] tools_4.1.0                   rsvd_1.0.5                    igraph_1.2.6                 
 [37] glue_1.4.2                    GenomeInfoDbData_1.2.6        dplyr_1.0.7                  
 [40] rappdirs_0.3.3                Rcpp_1.0.7                    vctrs_0.3.8                  
 [43] Biostrings_2.60.1             rhdf5filters_1.4.0            zellkonverter_1.2.1          
 [46] ExperimentHub_2.0.0           rtracklayer_1.52.0            DelayedMatrixStats_1.14.0    
 [49] stringr_1.4.0                 beachmat_2.8.0                mime_0.11                    
 [52] lifecycle_1.0.0               irlba_2.3.3                   restfulr_0.0.13              
 [55] ensembldb_2.16.3              statmod_1.4.36                XML_3.99-0.6                 
 [58] AnnotationHub_3.0.1           edgeR_3.34.0                  basilisk.utils_1.4.0         
 [61] zlibbioc_1.38.0               ProtGenerics_1.24.0           hms_1.1.0                    
 [64] promises_1.2.0.1              AnnotationFilter_1.16.0       yaml_2.2.1                   
 [67] curl_4.3.2                    reticulate_1.20               memoise_2.0.0                
 [70] biomaRt_2.48.2                stringi_1.7.3                 RSQLite_2.2.7                
 [73] BiocVersion_3.13.1            ScaledMatrix_1.0.0            GenomicFeatures_1.44.0       
 [76] filelock_1.0.2                BiocParallel_1.26.1           rlang_0.4.11                 
 [79] pkgconfig_2.0.3               bitops_1.0-7                  lattice_0.20-44              
 [82] purrr_0.3.4                   Rhdf5lib_1.14.2               GenomicAlignments_1.28.0     
 [85] bit_4.0.4                     tidyselect_1.1.1              magrittr_2.0.1               
 [88] R6_2.5.0                      generics_0.1.0                metapod_1.0.0                
 [91] DelayedArray_0.18.0           DBI_1.1.1                     withr_2.4.2                  
 [94] pillar_1.6.1                  KEGGREST_1.32.0               RCurl_1.98-1.3               
 [97] dir.expiry_1.0.0              tibble_3.1.3                  crayon_1.4.1                 
[100] utf8_1.2.2                    BiocFileCache_2.0.0           progress_1.2.2               
[103] locfit_1.5-9.4                grid_4.1.0                    blob_1.2.2                   
[106] digest_0.6.27                 xtable_1.8-4                  httpuv_1.6.1                 
```

**Comment by csoneson** [comment] 2021-07-28 20:07
Hm, I see. Not sure if it would help, but could you try to set the rownames and colnames of `myloom`?

**Comment by iheartfoosball** [comment] 2021-08-16 19:45
Hi Charlotte, so sorry for the slow reply. I'm (hopefully) finishing my PhD next week so I haven't had time to explore this thoroughly.

Thanks for the suggestion! The file was readable after setting the rownames and colnames :) I previously tried setting just the rownames but I hadn't tried doing both. Great idea.

I actually ended up using a different workflow; I'll comment again in a couple of weeks with a more detailed description.

Thanks again!
